version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - vikasa-network
    environment:
      - REACT_APP_API_URL=/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:3000"
    depends_on:
      - dynamodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - vikasa-network
    environment:
      - DATABASE_URL=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-east-1

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    networks:
      - vikasa-network
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:4.2
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  vikasa-network:
    driver: bridge
